name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: build
    steps:
      - name: Install git
        run: |
          sudo apt update && sudo apt install git

      - name: Clone SerenityOS repo
        run: |
          git clone https://github.com/SerenityOS/serenity.git

      - name: Install dependencies
        run: |
          sudo apt install build-essential cmake curl libmpfr-dev libmpc-dev libgmp-dev e2fsprogs ninja-build qemu-system-gui qemu-system-x86 qemu-utils ccache rsync unzip texinfo libssl-dev zlib1g-dev

      - name: Install GCC 13
        run: |
          sudo apt install gcc-13 g++-13

      - name: Compile SerenityOS
        run: |
          cd serenity
          bash ./Meta/serenity.sh build

      - name: Build SerenityOS image
        run: |
          cd serenity
          bash ./Meta/serenity.sh image
          ninja -C Build/x86_64 limine-image

      - name: Create new release and upload iso
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=$(date +%F)
          gh release create $DATE qemu_image