name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: build
    steps:
      - name: Install git
        run: |
          sudo apt update && sudo apt install git

      - name: Clone SerenityOS repo
        run: |
          git clone git@github.com:SerenityOS/serenity.git

      - name: Install requied packages
        run: |
          sudo apt install build-essential cmake curl libmpfr-dev libmpc-dev libgmp-dev e2fsprogs ninja-build qemu-system-gui qemu-system-x86 qemu-utils ccache rsync unzip texinfo libssl-dev

      - name: Install GCC 13
        run: |
          sudo apt install gcc-13 g++-13

      - name: Compile SerenityOS
        run: |
          cd serenity
          bash ./Meta/serenity.sh build

      - name: Create new release and upload iso
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create --draft REPLACEME *.iso