name: Build SerenityOS QEMU Image

on:
  # Umožňuje spustit workflow ručně přes webové rozhraní GitHubu (v záložce Actions)
  workflow_dispatch:

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        # Nainstaluje závislosti podle BuildInstructions.md (včetně fuse2fs a gcc-14)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake curl libmpfr-dev libmpc-dev libgmp-dev e2fsprogs ninja-build qemu-system-gui qemu-system-x86 qemu-utils ccache rsync unzip texinfo libssl-dev zlib1g-dev fuse2fs gcc-14 g++-14
        
      - name: Set environment variables
        # Nastaví vynuceně překladač na GCC-14 pro podporu C++26
        run: |
          echo "CC=gcc-14" >> $GITHUB_ENV
          echo "CXX=g++-14" >> $GITHUB_ENV

      - name: Build QEMU Image
        # Zkompiluje toolchain a vytvoří obraz disku (výchozí architektura x86_64 a překladač GNU)
        run: |
          ./Meta/serenity.sh image x86_64 GNU

      - name: Get current date
        id: date
        # Získá aktuální datum (ve formátu RRRR-MM-DD), které použije pro název releasu
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Compress QEMU Image
        # Zabalí vygenerovaný obraz disku (image) do ZIP archivu pro nahrání do Releases
        run: |
          cd Build/x86_64/
          zip -r serenity-qemu-image-${{ env.DATE }}.zip _disk_image
          
      - name: Create Release and Upload
        # Vytvoří Release s aktuálním datem a nahraje do něj zabalený obraz disku
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.DATE }}
          name: ${{ env.DATE }}
          files: Build/x86_64/serenity-qemu-image-${{ env.DATE }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}